name: pich
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - _x86_64-microarch-level=3
  - alsa-lib=1.2.15.1
  - asttokens=3.0.1
  - attr=2.5.2
  - binutils_impl_linux-64=2.45
  - binutils_linux-64=2.45
  - blas=1.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cmake=3.29.4
  - comm=0.2.3
  - conda-gcc-specs=12.4.0
  - cpython=3.11.14
  - cuda-cccl=13.1.78
  - cuda-cccl_linux-64=13.1.78
  - cuda-command-line-tools=12.4.1
  - cuda-compiler=13.1.0
  - cuda-crt-dev_linux-64=13.1.80
  - cuda-crt-tools=13.1.80
  - cuda-ctadvisor=13.1.80
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cudart-dev_linux-64=13.1.80
  - cuda-cudart-static=13.1.80
  - cuda-cudart-static_linux-64=13.1.80
  - cuda-cudart_linux-64=13.1.80
  - cuda-culibos-static=13.1.68
  - cuda-cuobjdump=13.1.80
  - cuda-cupti=12.4.127
  - cuda-cuxxfilt=13.1.80
  - cuda-documentation=12.4.127
  - cuda-driver-dev=13.1.80
  - cuda-driver-dev_linux-64=13.1.80
  - cuda-gdb=13.1.68
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.6.2
  - cuda-libraries-static=13.1.0
  - cuda-nsight=13.1.68
  - cuda-nvcc=13.1.80
  - cuda-nvcc-dev_linux-64=13.1.80
  - cuda-nvcc-impl=13.1.80
  - cuda-nvcc-tools=13.1.80
  - cuda-nvcc_linux-64=13.1.80
  - cuda-nvdisasm=13.1.80
  - cuda-nvml-dev=13.1.68
  - cuda-nvprof=12.4.127
  - cuda-nvprune=13.1.80
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvrtc-static=13.1.80
  - cuda-nvtx=12.4.127
  - cuda-nvvm-dev_linux-64=13.1.80
  - cuda-nvvm-impl=13.1.80
  - cuda-nvvm-tools=13.1.80
  - cuda-nvvp=12.4.127
  - cuda-opencl=13.1.80
  - cuda-opencl-dev=13.1.80
  - cuda-profiler-api=13.1.80
  - cuda-runtime=12.4.1
  - cuda-sanitizer-api=13.1.75
  - cuda-tileiras=13.1.80
  - cuda-toolkit=12.4.1
  - cuda-tools=12.4.1
  - cuda-version=13.1
  - cuda-visual-tools=12.6.2
  - cudnn=9.12.0.46
  - dbus=1.13.6
  - debugpy=1.8.19
  - decorator=5.2.1
  - eigen=3.4.0
  - executing=2.2.1
  - expat=2.7.3
  - fenics=2019.1.0
  - fenics-dijitso=2019.1.0
  - fenics-dolfin=2019.1.0
  - fenics-ffc=2019.1.0
  - fenics-fiat=2019.1.0
  - fenics-libdolfin=2019.1.0
  - fenics-ufl=2019.1.0
  - ffmpeg=4.3
  - fftw=3.3.10
  - filelock=3.20.2
  - fontconfig=2.14.2
  - freetype=2.12.1
  - gcc=12.4.0
  - gcc_impl_linux-64=12.4.0
  - gcc_linux-64=12.4.0
  - gds-tools=1.16.0.49
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.13
  - gxx=12.4.0
  - gxx_impl_linux-64=12.4.0
  - gxx_linux-64=12.4.0
  - h2=4.3.0
  - h5py=3.13.0
  - hdf5=1.14.3
  - hpack=4.1.0
  - hyperframe=6.1.0
  - hypre=2.28.0
  - icu=73.2
  - idna=3.11
  - ipykernel=7.1.0
  - ipython=9.9.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - jupyterlab_widgets=3.0.16
  - kernel-headers_linux-64=6.12.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libaec=1.1.4
  - libamd=3.3.3
  - libblas=3.9.0
  - libboost=1.84.0
  - libboost-headers=1.90.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcap=2.77
  - libcblas=3.9.0
  - libccolamd=3.3.4
  - libcholmod=5.3.1
  - libcolamd=3.3.4
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcublas-static=13.2.0.9
  - libcudnn=9.12.0.46
  - libcudnn-dev=9.12.0.46
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcufft-static=12.1.0.31
  - libcufile=1.16.0.49
  - libcufile-dev=1.16.0.49
  - libcufile-static=1.16.0.49
  - libcurand=10.4.1.34
  - libcurand-dev=10.4.1.34
  - libcurand-static=10.4.1.34
  - libcurl=8.8.0
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusolver-static=12.0.7.41
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libcusparse-static=12.7.2.19
  - libcxsparse=4.4.1
  - libdeflate=1.17
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libfabric=2.4.0
  - libfabric1=2.4.0
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-devel_linux-64=12.4.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.80.2
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=2.0.0
  - libklu=2.3.5
  - liblapack=3.9.0
  - libldl=3.3.2
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.58.0
  - libnl=3.11.0
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnpp-static=13.0.2.21
  - libnsl=2.0.1
  - libnvfatbin=13.1.80
  - libnvfatbin-dev=13.1.80
  - libnvfatbin-static=13.1.80
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjitlink-static=13.1.80
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libnvjpeg-static=13.0.2.28
  - libnvptxcompiler-dev=13.1.80
  - libnvptxcompiler-dev_linux-64=13.1.80
  - libopengl=1.7.0
  - libparu=1.0.0
  - libpng=1.6.43
  - libptscotch=7.0.4
  - librbio=4.3.4
  - libsanitizer=12.4.0
  - libscotch=7.0.4
  - libsodium=1.0.20
  - libspex=3.2.3
  - libspqr=4.3.4
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=12.4.0
  - libstdcxx-ng=15.2.0
  - libsuitesparseconfig=7.10.1
  - libsystemd0=258.3
  - libtiff=4.5.0
  - libudev1=258.3
  - libumfpack=6.3.5
  - libuuid=2.41.3
  - libuv=1.51.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.5.0
  - libxkbfile=1.1.0
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=3.0.3
  - matplotlib-inline=0.2.1
  - metis=5.1.0
  - mkl=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpi4py=3.1.6
  - mpmath=1.3.0
  - mumps-include=5.6.2
  - mumps-mpi=5.6.2
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.6
  - networkx=3.6.1
  - nsight-compute=2024.1.1.4
  - nspr=4.38
  - nss=3.100
  - numpy=1.26.4
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openmpi=4.1.6
  - openssl=3.6.0
  - packaging=25.0
  - parmetis=4.0.3
  - parso=0.8.5
  - pcre2=10.43
  - petsc=3.20.6
  - petsc4py=3.20.5
  - pexpect=4.9.0
  - pillow=9.4.0
  - pip=25.3
  - pkg-config=0.29.2
  - pkgconfig=1.5.5
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.1
  - pthread-stubs=0.4
  - ptscotch=7.0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11=2.12.0
  - pybind11-global=2.12.0
  - pycparser=2.22
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0.post0
  - python-gil=3.11.14
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - rdma-core=60.0
  - readline=8.3
  - requests=2.32.5
  - rhash=1.4.6
  - scalapack=2.2.0
  - scotch=7.0.4
  - setuptools=80.9.0
  - six=1.17.0
  - slepc=3.20.2
  - slepc4py=3.20.2
  - stack_data=0.6.3
  - suitesparse=5.10.1
  - superlu=7.0.1
  - superlu_dist=8.2.1
  - sysroot_linux-64=2.39
  - tbb=2021.13.0
  - tk=8.6.13
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - ucc=1.6.0
  - ucx=1.19.1
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - xcb-util=0.4.0
  - xcb-util-cursor=0.1.4
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-compositeproto=0.4.2
  - xorg-damageproto=1.2.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.5
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrandr=1.5.2
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-randrproto=1.5.0
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-util-macros=1.20.2
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - attrs==25.4.0
      - bpy==5.0.1
      - contourpy==1.3.3
      - cvxopt==1.3.2
      - cycler==0.12.1
      - cython==3.2.4
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - gmsh==4.15.0
      - kiwisolver==1.4.9
      - lightning==2.6.0
      - lightning-utilities==0.15.2
      - markdown-it-py==4.0.0
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - meshio==5.3.5
      - multidict==6.7.0
      - multipledispatch==1.0.0
      - pandas==2.3.3
      - pina-mathlab==0.1.2.post2501
      - propcache==0.4.1
      - pyparsing==3.3.1
      - pyprojroot==0.3.0
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - rbnics==0.2.0
      - rich==14.2.0
      - scipy==1.13.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - torchmetrics==1.8.2
      - tqdm==4.67.1
      - tzdata==2025.3
      - yarl==1.22.0
